#!/bin/bash
# Performance Audit Script
# Generates KPI-based performance report

set -e

# Configuration
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
AGENT_ROOT="$(dirname "$(dirname "$SCRIPT_DIR")")" # From /skills/audit-mastery/scripts/ to /

DAYS=${1:-7}  # Default: last 7 days
START_DATE=$(date -d "$DAYS days ago" +%Y-%m-%d)
END_DATE=$(date +%Y-%m-%d)
REPORT_DIR="$AGENT_ROOT/reports/performance"
REPORT_FILE="$REPORT_DIR/$(date +%Y-%m-%d)-audit.md"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo "🔍 Generating Performance Audit Report..."
echo "📅 Period: $START_DATE to $END_DATE"

# KPI 1: Velocity (Tasks Completed)
echo "📊 Calculating Velocity..."
TASKS_COMPLETED=$(find "$AGENT_ROOT/workspace"/*/history/tasks/2026/01/ -name "*.md" -type f -exec grep -l "✅\|DONE" {} \; 2>/dev/null | wc -l)
if [ "$TASKS_COMPLETED" -eq 0 ]; then
    TASKS_PER_WEEK=0
else
    TASKS_PER_WEEK=$(echo "scale=1; $TASKS_COMPLETED / ($DAYS / 7)" | bc)
fi

if (( $(echo "$TASKS_PER_WEEK >= 8" | bc -l) )); then
    VELOCITY_SCORE="Excellent"
    VELOCITY_COLOR=$GREEN
elif (( $(echo "$TASKS_PER_WEEK >= 4" | bc -l) )); then
    VELOCITY_SCORE="Average"
    VELOCITY_COLOR=$YELLOW
else
    VELOCITY_SCORE="Low"
    VELOCITY_COLOR=$RED
fi

# KPI 2: Quality (Bug Rate - Placeholder)
# TODO: Integrate with Jira to count bugs
BUGS_INTRODUCED=1
BUG_RATE=$(echo "scale=2; $BUGS_INTRODUCED / ($TASKS_COMPLETED / 10)" | bc)
QUALITY_SCORE="Average"  # Placeholder
QUALITY_COLOR=$YELLOW

# KPI 3: Efficiency (Commit Frequency)
echo "📊 Calculating Consistency..."
COMMIT_DAYS=$(git -C "$AGENT_ROOT" log --since="$START_DATE" --until="$END_DATE" --format="%ad" --date=short | sort -u | wc -l)
WORKING_DAYS=$DAYS
CONSISTENCY_PCT=$(echo "scale=0; ($COMMIT_DAYS / $WORKING_DAYS) * 100" | bc)

if (( CONSISTENCY_PCT >= 90 )); then
    CONSISTENCY_SCORE="Excellent"
    CONSISTENCY_COLOR=$GREEN
elif (( CONSISTENCY_PCT >= 70 )); then
    CONSISTENCY_SCORE="Average"
    CONSISTENCY_COLOR=$YELLOW
else
    CONSISTENCY_SCORE="Low"
    CONSISTENCY_COLOR=$RED
fi

# Calculate Overall Score
EXCELLENT_COUNT=0
[[ "$VELOCITY_SCORE" == "Excellent" ]] && ((EXCELLENT_COUNT++))
[[ "$QUALITY_SCORE" == "Excellent" ]] && ((EXCELLENT_COUNT++))
[[ "$CONSISTENCY_SCORE" == "Excellent" ]] && ((EXCELLENT_COUNT++))

if (( EXCELLENT_COUNT >= 2 )); then
    OVERALL="EXCELLENT"
    OVERALL_COLOR=$GREEN
elif (( EXCELLENT_COUNT >= 1 )); then
    OVERALL="AVERAGE"
    OVERALL_COLOR=$YELLOW
else
    OVERALL="LOW"
    OVERALL_COLOR=$RED
fi

# Generate Report
cat > "$REPORT_FILE" << EOF
# 📊 Performance Audit Report

**Period**: $START_DATE to $END_DATE  
**Generated**: $(date +"%Y-%m-%d %H:%M:%S")  
**Overall Score**: **$OVERALL**

---

## Summary

| Pillar       | Score              | Metric                          |
|--------------|--------------------|---------------------------------|
| Velocity     | $VELOCITY_SCORE    | $TASKS_PER_WEEK tasks/week      |
| Quality      | $QUALITY_SCORE     | $BUG_RATE bugs/10 tasks         |
| Efficiency   | N/A                | (Manual review required)        |
| Impact       | N/A                | (Jira priority analysis needed) |
| Consistency  | $CONSISTENCY_SCORE | $CONSISTENCY_PCT% commit days   |

---

## Detailed Analysis

### 1. Velocity: **$VELOCITY_SCORE**
- **Tasks Completed**: $TASKS_COMPLETED
- **Tasks per Week**: $TASKS_PER_WEEK
- **Target**: ≥ 8 tasks/week (Excellent)

### 2. Quality: **$QUALITY_SCORE**
- **Bugs Introduced**: $BUGS_INTRODUCED (estimated)
- **Bug Rate**: $BUG_RATE bugs/10 tasks
- **Target**: < 1 bug/10 tasks (Excellent)

### 3. Consistency: **$CONSISTENCY_SCORE**
- **Days with Commits**: $COMMIT_DAYS / $WORKING_DAYS
- **Percentage**: $CONSISTENCY_PCT%
- **Target**: ≥ 90% (Excellent)

---

## Recommendations

EOF

# Add recommendations based on scores
if [[ "$VELOCITY_SCORE" == "Low" ]]; then
    echo "- **Velocity**: Break down tasks into smaller atomic units (<2 hours each)." >> "$REPORT_FILE"
fi

if [[ "$CONSISTENCY_SCORE" == "Low" ]]; then
    echo "- **Consistency**: Commit daily, even for WIP. Use \`git commit -m 'WIP: ...\`." >> "$REPORT_FILE"
fi

if [[ "$OVERALL" == "EXCELLENT" ]]; then
    echo "- **Keep it up!** You're performing at an excellent level. Focus on maintaining this momentum." >> "$REPORT_FILE"
fi

echo "" >> "$REPORT_FILE"
echo "---" >> "$REPORT_FILE"
echo "*Generated by performance-audit-mastery skill*" >> "$REPORT_FILE"

# Display Summary
echo ""
echo -e "${OVERALL_COLOR}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${OVERALL_COLOR}  Overall Score: $OVERALL${NC}"
echo -e "${OVERALL_COLOR}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "  Velocity:    ${VELOCITY_COLOR}$VELOCITY_SCORE${NC} ($TASKS_PER_WEEK tasks/week)"
echo -e "  Quality:     ${QUALITY_COLOR}$QUALITY_SCORE${NC} ($BUG_RATE bugs/10 tasks)"
echo -e "  Consistency: ${CONSISTENCY_COLOR}$CONSISTENCY_SCORE${NC} ($CONSISTENCY_PCT% commit days)"
echo ""
echo "📄 Full report saved to: $REPORT_FILE"
echo ""
